### ISSUE TITLE
Getting Error When Selecting Avatar Photo without photo

### ISSUE THREAD

**Issue by prajot03** [readyplayerme/rpm-unity-sdk-avatar-creator#31]
**Describe the bug**

1.: Selected Male version
2.: 
**We failed to load the photo (we bet you look great, though)! Please try using a different file."}
https://api.readyplayer.me/v2/avatars**

{"type":"AbsynthError","status":500,"message":"We failed to load the photo (we bet you look great, though)! Please try using a different file."}
https://api.readyplayer.me/v2/avatars

**Comment by rYuuk** [comment]
Hi, this is happening because base64image is new a required field and default avatars API has been changed. Its fixed in latest release v0.4.0.

**Comment by fantastxu** [comment]
> Hi, this is happening because base64image is new a required field and default avatars API has been changed. Its fixed in latest release v0.4.0.

Thank you for the quick fix  @rYuuk , the v0.4.0 has already fix the problem, but the version number in the package still stays on 0.3.1.  ;)

**Comment by rYuuk** [comment]
The version number has been fixed.
