### ISSUE TITLE
The 0.4.0 sample causes a runtime error on android devices.

### ISSUE THREAD

**Issue by fantastxu** [readyplayerme/rpm-unity-sdk-avatar-creator#33]
**Describe the bug**
The 0.4.0 sample causes a runtime error on android devices.

I can create avatars in Unity Editor without problem. 
On android devices, I got runtime errors as follows:

![image](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/assets/2860633/0927b38e-5993-497b-9512-8d1de0da4d9d)

**Comment by rYuuk** [comment]
I tested it on my Android device and it appears to be functioning properly. May I ask which version you are currently using?

**Comment by fantastxu** [comment]
I made a new clean Unity project and tested it again, but got the same error.
Unity version: 2021.3.24f1
Installed package:
![image](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/assets/2860633/9461f03a-fad3-4a24-8381-c239cc7d01b8)
Compiled for Android APK. 

I also attached the APK, the Unity log, and the Unity project here. It will be great if you can look at it. 
Thanks in advance.

[log.txt](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/files/11961764/log.txt)
[RPM_Creator_Test.zip](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/files/11961747/RPM_Creator_Test.zip)
[RPMCreator.apk.zip](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/files/11961760/RPMCreator.apk.zip)

**Comment by rYuuk** [comment]
This error was occurring on webgl, it was related to serialization of array in netwonsoft json. I fixed it on develop branch,
will it be possible for you to try develop branch?

https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/pull/34

**Comment by fantastxu** [comment]
Got another different deserialized error
![image](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/assets/2860633/2705c9a6-c657-45cd-850a-5e79d98a9334)

![image](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/assets/2860633/8058fae1-6e76-46cb-b0ef-129a348521a7)

**Comment by fantastxu** [comment]
Hi 
Is there any update about this issue? If you need any tests, please tell me.

**Comment by rYuuk** [comment]
Thanks for investigating, we will look into it. It would be great if you could also provide the log file for the above mentioned error.

**Comment by rYuuk** [comment]
Please go ahead and make a PR.
