### ISSUE TITLE
The given key 'bottom' was not present in the dictionary.

### ISSUE THREAD

**Issue by prajot03** [readyplayerme/rpm-unity-sdk-avatar-creator#43]
The given key 'bottom' was not present in the dictionary.
![image](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/assets/38028200/d1168cf4-57d0-4f43-8204-751bf3675650)
@rYuuk 

**To Reproduce**
1. Imported RPM core  package https://github.com/readyplayerme/rpm-unity-sdk-core.git Version 3.2.1
2. Imported Creator Package https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator.git  Version 0.5.0
3. Load QuickStartCreator  and Load AvatarCreatorExample Scene
4. Click on Play
5. Select the Male Female Version and Load without Photo and Select any Default avatar 
6. See error  The given key 'bottom' was not present in the dictionary.

**Desktop (please complete the following information):**
 - Ready Player Me Avatar Creator version
 - Ready Player Me Core version
 - Ready Player Me Avatar Loader version
 - Ready Player Me WebView version
 - glTFast version
 - Unity Editor version [e.g. 2021.3.28f1]
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.1.12]
 - Operating System [Windows]
 - Platform: [Editor]

**Comment by rYuuk** [comment]
Hi, this will be fixed in next release. We have an open branch release/v1.0.0 with this fix, which will be merged after the testing is completed.

**Comment by rYuuk** [comment]
This is fixed in current released. Closing the issue.
